apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appLabel }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.image.port }}
  type: ClusterIP