apiVersion: batch/v1
kind: Job
metadata:
  name: content-writer
  namespace: my-namespace
spec:
  template:
    spec:
      containers:
        - name: writer
          image: busybox
          command: ["sh", "-c", "echo '<h1>Hello from HERE!</h1>' > /mnt/index.html"]
          volumeMounts:
            - name: html
              mountPath: /mnt
      restartPolicy: OnFailure
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: my-pvc
