apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
  namespace: my-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "pv"  # Use the default storage class
