apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: my-namespace
type: Opaque
stringData:
  password: cGFzc3dvcmQ=     # base64 for "password"
  apiKey: YWJjMTIzNDU=       # base64 for "abc12345"

# WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
  # Store secrets in Vault (secrets manager), not in your YAML files.
  # And then in your Kubernetes manifests (like secret.yaml or deployment.yaml), you either:

  # Use placeholders that get populated dynamically
  # OR
  # Don’t define secrets at all in YAML — let a controller fetch them from Vault and inject into pods at runtime.

  # or Use Sealed Secrets