apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-namespace
spec:
  selector:
    app: my-app # This will select the nginx-pod based on the label my-app
  ports:
    - protocol: TCP
      port: 80  # The port on which the service will be accessible
      targetPort: 80  # The port on the pod to which traffic will be forwarded
      nodePort: 30080  # Exposed on each node
  type: NodePort  # Exposes the service outside the cluster
  