apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-configmaps-binding
  namespace: my-namespace
subjects:
  - kind: ServiceAccount
    name: app-sa
    namespace: my-namespace
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
